version: '3.5'

services:
  web:
    build: .
    container_name: nyiltnap
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    expose:
      - 3000
    networks:
      - postgres

  db:
    image: postgres:14-alpine
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres # !!!!
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U default" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
